environment:
  DATABASE_URL: ${DATABASE_URL}
  DATABASE_USER: ${DATABASE_USER}
  DATABASE_NAME: ${DATABASE_NAME}
  DATABASE_PORT: ${DATABASE_PORT}
  DATABASE_PASSWORD: ${DATABASE_PASSWORD}
parameters: { }
packages:
  - name: user
    environment: { }
    parameters: { }
    annotations: { }
    actions:
      - name: auth
        binary: false
        main: ''
        runtime: 'go:default'
        web: true
        parameters: { }
        environment: { }
        annotations: { }
        limits: { }
      - name: register
        binary: false
        main: ''
        runtime: 'go:default'
        web: true
        parameters: { }
        environment: { }
        annotations: { }
        limits: { }
      - name: migrate
        binary: false
        main: ''
        runtime: 'go:default'
        web: true
        parameters: { }
        environment: { }
        annotations: { }
        limits: { }
  - name: gallery
    environment: { }
    parameters: { }
    annotations: { }
    actions:
      - name: single
        binary: false
        main: ''
        runtime: 'go:default'
        web: true
        parameters: { }
        environment: { }
        annotations: { }
        limits: { }